# Generated by Django 4.2.2 on 2023-07-11 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DRP", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="DateOfJoining",
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
