# Generated by Django 4.2.2 on 2023-07-12 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DRP", "0002_alter_employee_dateofjoining"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="DateOfJoining",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="PhotoFileName",
            field=models.ImageField(upload_to=""),
        ),
    ]
